spring:
  application:
    name: api-gateway
  profiles:
    active: api_gateway
  cloud:
    config:
      name: api-gateway,config-client
      uri: http://config-server:8888
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

