spring:
  application:
    name: kafka-streams-service
  profiles:
    active: kafka_streams_service
  cloud:
    config:
      name: kafka-streams-service,config-client
      uri: http://localhost:8888
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://localhost:8888