spring:
  application:
    name: reactive-elastic-query-service
  profiles:
    active: reactive_elastic_query
  cloud:
    config:
      name: reactive-elastic-query-service,config-client
      uri: http://localhost:8888
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://localhost:8888

