spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  cloud:
    config:
      name: elastic-query-web-client,config-client
      uri: http://localhost:8888
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://localhost:8888

